name: Arduino Library CI

permissions:
  contents: write  # Grants write permissions for contents (needed to create releases)

on:
  push:
    branches:
      - main  # Runs on main branch pushes only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Up Git User as Committer
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: Install Arduino AVR Core
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Run build script
      run: |
        bash build.sh

    - name: Run Version Increment Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Run the version increment script
        bash version-increment.sh

        # Use HTTPS with token for authenticated push
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push origin main --tags